### ISSUE TITLE
Lumberjack module logging wrong year 

### ISSUE THREAD

**Issue by reversekick** [natefinch/lumberjack#128]
time="4040-03-04 00:35:45.303004" level=info msg="Current Connectivity state SUCCESS"

If you see the above -- the Year is wrong the reason for this is -- likely an issue in the library ? 
https://play.golang.org/p/MwIcUG74NBD

**Comment by 2rigor** [comment]
the same as at https://github.com/sirupsen/logrus/issues/1242

**Comment by natefinch** [comment]
I literally just use time.now. It must be the system clock is wrong.

**Comment by natefinch** [comment]
Oh yeah, looking at the other bug... You have to read the time formatting very carefully. If you want a 4 digit year. The format should say 2006

**Comment by reversekick** [comment]
Initially thought that it was Lumberjack issue & had openned it here and later found that is is comming form siruspen/logrus and openned there.. Forgot to close here.
