### ISSUE TITLE
If one log routine is switching files, will it affect the writing of other routine?

### ISSUE THREAD

**Issue by longbozhan** [natefinch/lumberjack#149]
As the Write func impl,  will lock mutex, if this operation waste too much time, such as compress, other routine will block？

**Comment by natefinch** [comment]
Compress is done in a separate goroutine, so it won't block, specifically for this reason. At most, write will rename the current file and open a new one. That's still a lot for a single log write, but way shorter than than compression, and it shouldn't happen very often.
