### ISSUE TITLE
After the log file is rotated, the inode information changes, resulting in the generation of zombie files

### ISSUE THREAD

**Issue by singgel** [natefinch/lumberjack#187]
I use lumberjack to record the log of the golang application. 
At the same time, the standard output 1 and standard error output logs started by the process nohup are also redirected to the application log of golang app.
but after the rotated, the inode information of the log file has changed. 
The fd 1 & 2 handle of the process still refers to the old inode, resulting in the generation of zombie files. 

Is there have any suggestions for solving it?

example:
#> ll -ilh
67110914 -rw-r--r-- 1 admin admin 563M Jun  7 11:01 api.log
67110924 -rw-r--r-- 1 admin admin 977M Jun  7 10:48 api.log.1

I want to keep the inode of the api.log log unchanged

**Comment by natefinch** [comment]
It sounds like you're writing to the same log file from outside the Go application. Lumberjack specifically does not support that. It tracks the size of the file internally, and as you have noticed, will change the name of the file and start writing to a new file when it rotates.

It's honestly probably not a good idea to have two processes writing to the same log file anyway, as they could have overlapping or interleaved writes, which would mangle the output.

If I'm misunderstanding you, feel free to clarify.

**Comment by singgel** [comment]
Yes, that's what you understand. I will handle the logs of the two processes separately. Thank you very much.
