### ISSUE TITLE
Cannot use lumberjack in Go WebServer App?

### ISSUE THREAD

**Issue by duongphuhiep** [natefinch/lumberjack#25]
"Lumberjack assumes that only one process is writing to the output files. Using the same lumberjack configuration from multiple processes on the same machine will result in improper behavior."

Is it means that we shouldn't use Lumberjack in Golang WebServer or any Go application with Go routines concurrently write to the log file?

thank you

**Comment by natefinch** [comment]
Oh no no. Lumberjack is totally thread/goroutine safe from a single process. Any number of goroutines can write to it safely. It is only if multiple processes write to it that you can experience problems.

**Comment by duongphuhiep** [comment]
YES great! thank you very much

**Comment by pchico83** [comment]
@natefinch what would be an alternative if multiple processes write to the same log file? we are facing this issue in windows

**Comment by natefinch** [comment]
Well, you probably shouldn't do that anyway. You can easily get interspersed writes, like one process writes the first half of a log message, then the other process writes the first half of their log message, then both write the second half... and that even assumes that one doesn't just lock the file and exclude the other.

The only way I can think to make that work is to have a third process that both send their log messages to, and it serializes them, and then it handles the log rotation. But it seems easier just to let each process have its own log file.
