### ISSUE TITLE
add_daily_log_daily

### ISSUE THREAD

**Issue by cyuanxin** [natefinch/lumberjack#27]
hello! i have pull request.i add daily_log_daily to the project.

**Comment by natefinch** [comment]
Hi!  Thanks so much for the work you did for the contribution.  Unfortunately, I don't think rotating based on passage of time is a good idea.  My argument is fully detailed here: https://github.com/natefinch/lumberjack/issues/17

**Comment by cyuanxin** [comment]
ok . thanks for your project and your response.
