### ISSUE TITLE
Set perms on file

### ISSUE THREAD

**Issue by ghost** [natefinch/lumberjack#33]
I need to set the perms on the log file to 666.  How should I achieve this? I can write code to do it in my app, but at what point should I do it? Is the file created when I instantiate the logger object or at the first log entry write? and does lumberjack maintain the perms when the file rolls? Perhaps I should simply create a empty file with the correct perms before starting lumberjack?

**Comment by natefinch** [comment]
Your guesses are accurate - lumberjack maintains the permissions of the
original file, and when it rolls it creates a new file with the same
permissions, so you can just create the file with the right permissions and
then give that path to lumberjack, and it'll all work correctly.
