### ISSUE TITLE
lumberjack_test.go:377: exp: 1 (int), got: 2 (int)

### ISSUE THREAD

**Issue by brunoqc** [natefinch/lumberjack#5]
I'm not sure if this issue is related but my applications are not logging anymore since I updated to go 1.4rc1.

If it's a bug in Go 1.4, you may want to hurry since "[it's] scheduled to be released on 1 Dec 2014".

go version go1.4rc1 windows/amd64

```
go get github.com/natefinch/lumberjack

cd %GOPATH%\src\github.com\natefinch\lumberjack

d:\Dev\go\gopath\src\github.com\natefinch\lumberjack>go test
lumberjack_test.go:377: exp: 1 (int), got: 2 (int)
--- FAIL: TestMaxAge (0.06s)
FAIL
exit status 1
FAIL    github.com/natefinch/lumberjack 0.212s
```

**Comment by natefinch** [comment]
Sounds like this should have been closed a long time ago, so I'm doing so now.  Thanks for reporting it, regardless.  Any and all feedback is much appreciated.
