### ISSUE TITLE
Write a file header on each new file created

### ISSUE THREAD

**Issue by DnlLrssn** [natefinch/lumberjack#50]
I need a file header to be written each time a new file is created. I don't see a way to do this, especially on rotate. Will add a PR with a suggested solution.

**Comment by DnlLrssn** [comment]
https://github.com/natefinch/lumberjack/pull/51

**Comment by natefinch** [comment]
I'm curious what the use case is for this?  What do you want to write in the header?

**Comment by DnlLrssn** [comment]
In my case I want to write in a CSV format for easily reading the log into a analytics tool. For this I need a header for what each column represent. However I figured there might be other reason why you might do this and it could be useful for others.

**Comment by natefinch** [comment]
That's an interesting use case...

**Comment by natefinch** [comment]
So, upon thinking about this... I think your specific use case is too specific.  The tool you're importing data into should give you the option of setting column names.  I don't think this feature is useful in enough cases to merit an API change.

**Comment by DnlLrssn** [comment]
Had to think and experiment quite a bit, but I have a solution now which will not require the CSV header. Thank you for considering the request.
