### ISSUE TITLE
Logging mutli-files

### ISSUE THREAD

**Issue by LeaBloodForged** [natefinch/lumberjack#53]
Hi,
I wanted to know if it was possible to write the logs to differents files.
I would like to write the log.Error in one file and the log.Info in another file.
Thanks in advance.

**Comment by natefinch** [comment]
this all depends on what logging library you use. lumberjack doesn't know or care what logger you're using. it just wraps a file. you could have two instances of lumberjack wrapping two different files... but getting info or error is at the log library level and you'll have to consult the docs for your particular library.
