### ISSUE TITLE
change dir mod from 0744 to 0755

### ISSUE THREAD

**Issue by sysulq** [natefinch/lumberjack#59]
```
drwxr--r-- 2 www  www        20 Dec 26 09:50 logs
```

When set filename to `logs/app.log`, we cannot use `www` user to access `logs` directory...

https://github.com/natefinch/lumberjack/blob/aee4629129445bbdfb69aa565537dcfa16544311/lumberjack.go#L209

**Comment by caibirdme** [comment]
The same problem, 0755 would be better

**Comment by spacewander** [comment]
This was fixed by https://github.com/natefinch/lumberjack/pull/68.
So can we close it now?

**Comment by sysulq** [comment]
sure
