### ISSUE TITLE
Want New Options: do not delete log files when reach MaxAge but not reach MaxeBackups

### ISSUE THREAD

**Issue by vikyd** [natefinch/lumberjack#66]
settings:
```go
FileName:    "t.log",
MaxAge:      7,
MaxBackups:  3,
```

my log files:
```
t-2018-09-03T00-00-00.00.log
t-2018-08-20T00-00-00.00.log
```

current time: 
```
2018-09-04
```

I don't want to delete the second log file `t-2018-08-20T00-00-00.00.log`, because there are not too many files.

If there an option to archive it, it will be nice.

**Comment by xiegeo** [comment]
Shouldn't increase MaxAge work for you?

**Comment by vikyd** [comment]
@xiegeo  Yes!
