### ISSUE TITLE
go get fails because it can't find go-import tags

### ISSUE THREAD

**Issue by erbesharat** [natefinch/lumberjack#67]
``go get gopkg.in/natefinch/lumberjack.v2`` fails with the following output:

```shell
package gopkg.in/natefinch/lumberjack.v2: unrecognized import path "gopkg.in/natefinch/lumberjack.v2" (parse https://gopkg.in/natefinch/lumberjack.v2?go-get=1: no go-import meta tags ())
```

**Comment by natefinch** [comment]
This was a brief issue with one of github's machines going wonky: https://github.com/niemeyer/gopkg/issues/63

Should be fixed now.
