### ISSUE TITLE
default log permissions are too permissive

### ISSUE THREAD

**Issue by JAORMX** [natefinch/lumberjack#82]
The default permissions for the logs are set to 644, which is very permissive, as anyone can read the log files; which can be a security issue depending on the context.

I propose having a default of 600, which allows the application to read and write its own logs; and leaving root/admin users still with the ability to read the logs (which would normally need to see the logs).

**Comment by natefinch** [comment]
100% agree

**Comment by natefinch** [comment]
Just FYI, you can get around this in the current system by creating the original file yourself with the permissions you want, and then lumberjack will respect those and copy them to any new file it creates.

**Comment by JAORMX** [comment]
@natefinch right, it's not a blocking issue thanks to that.

I think the new defaults basically close this issue
